### ISSUE TITLE
URL paths give project paths

### ISSUE THREAD

**Issue by ghost** [ndelphit/apkurlgrep#1]
Hi there

First of all, nice project.
I've tested it on some apps, seems like it project paths into the URL paths, is there any way to fix that?

e.g.
`Ljava/util/WeakHashMap
Ljava/lang/Object
Ljava/lang/Enum
Landroid/arch/core/internal/FastSafeIterableMap
Ljava/lang/ref/WeakReference
Ljava/util/ArrayList
Landroid/util/SparseArray
Ljava/util/HashSet
Ljava/util/List`

**Comment by ndelphit** [comment]
Hi,
Thank you for your assessment, I really appreciate it!

I think this can be fixed by adding a parameter `-f --filter=slash, uppercase`.
This should help filter results from extracting by condition:

- `[slash]` - the first character in the string should be "/"
- `[uppercase]` - the string should not have any uppercase characters

I will add this feature as optional, because some of the interesting results may be loosed.

**Comment by ndelphit** [comment]
Also, could you please provide me a target APK which is have this type of result? This may help me to understand better where is the problem.

**Comment by ghost** [comment]
Sorry for the late answer,  it was the Reddit APK back then.
